// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqOBmCD7jtD9R3Va4sNg7WCWNkDtXyM4',
    appId: '1:802253720364:web:864c865b9b8cab5bc8fa89',
    messagingSenderId: '802253720364',
    projectId: 'loct-app',
    authDomain: 'loct-app.firebaseapp.com',
    storageBucket: 'loct-app.appspot.com',
    measurementId: 'G-RW4LWTFDSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-W3VmlNUzodVuMXkfnMADukAffw9u7s',
    appId: '1:802253720364:android:a7f0efc7c8462693c8fa89',
    messagingSenderId: '802253720364',
    projectId: 'loct-app',
    storageBucket: 'loct-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5ynQ-Fix7-D_oGoqRQDuqRw5_80RnME',
    appId: '1:802253720364:ios:83b3acb9b7362529c8fa89',
    messagingSenderId: '802253720364',
    projectId: 'loct-app',
    storageBucket: 'loct-app.appspot.com',
    iosBundleId: 'com.example.loc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5ynQ-Fix7-D_oGoqRQDuqRw5_80RnME',
    appId: '1:802253720364:ios:d5d2a9094181e5e5c8fa89',
    messagingSenderId: '802253720364',
    projectId: 'loct-app',
    storageBucket: 'loct-app.appspot.com',
    iosBundleId: 'com.example.loc.RunnerTests',
  );
}
